#!~/../usr/bin/bash

##############################color
m="\e[0;31m"      # merah           # red
k="\e[0;33m"      # kuning          # yellow
h="\e[0;32m"      # hijau           # green
b="\e[0;34m"      # biru            # blue
lm="\e[1;31m"     # merah terang    # pink
lk="\e[1;33m"     # kuning terang   # bright yellow
lh="\e[1;32m"     # hijau terang    # light green
lb="\e[1;34m"     # langit biru     # blue sky
n="\e[0m"         # netral          # neutral
w="\e[1;37m"


if [ -d /data/data/com.termux/files/usr/share/penda_pl ];then
      echo -e ${m} "Already Installed !!"
      exit 0
else
      clear
      cd
      mv ../usr/share/penda_pl/penda ../usr/bin/
      mv ../usr/share/penda_pl/penda-install ../usr/bin/
      chmod +x ../bin/penda
      chomd +x ../penda-install
      mkdir .penda
      mv ../usr/share/penda_pl/update.sh .penda/
      rm -rf ~/Penda-Official
      mv -f ../usr/share/penda_pl/manpage/penda.1 ../usr/share/man/man1/
      gzip -ff ../usr/share/man/man1/penda.1 
      makewhatis /data/data/com.termux/files/usr/share/man
      cd
      echo -e ${h} "Succesfully Installed !!"
fi
